### PR TITLE
Add parameter to prevent exports/outputs being generated

### PR DESCRIPTION
**Pull request by cintiadrrezdy**
So here's my problem. 

I have a project that deploy feature branches as new stacks. 
I do have all feature branches as the same EnvironmentName, and I don't have different configuration per feature branch. 

So changing parameters for me is trivial for feature branches vs master. But it's not easy to deploy a different config file per branch, as I'd need to generate it during build time. 

Is this an acceptable change? I believe it shouldn't break anything. 

You should be able to edit the PR with anything you need.

### CODE REVIEW

**Comment by cintiadrrezdy** [comment]
@Guslington / @jaredbrook  / @timhassett


Is this an acceptable PR?

**Comment by Guslington** [comment]
@cintiadrrezdy in your pipeline, what if you create the feature stacks using the feature name as the EnvironmentName rather than sharing environment names? Is there a reason you wan to keep the EnvironmentName the same across feature stacks?

**Comment by cintiadrrezdy** [comment]
Good question, I should have made it more clear. 

Base2 extended this component to few more features I needed, and it relies on a lot of shared resources from the same environment. 

For example, security group and loadbalancer. 
It's not a completely standalone branch, just a subset of resources is created for the feature branch. 

Not that we cannot change it, but having the output for me turned out to be a breaking change.

**Comment by Guslington** [comment]
@cintiadrrezdy my only issue is avoiding too many cloudformation parameters as that can cause issues and was just wondering if we could solve this another way

**Comment by cintiadrrezdy** [comment]
I tried to spend some time (what ended up a few hours) to attempt to use different environment names per branch. 

I got really close, but I got stuck on what _seems_ to be a limitation on cloudformation. 

My application stack is calling the hl-ecs-component (the one that inherits from this one) with the following parameter:

`    parameter name: 'PrivateDnsZoneId', value:
      FnIf(
        "isFeature",
        FindInMap('EnvironmentConfig','dev','PrivateDnsZoneId'),
        FindInMap('EnvironmentConfig',Ref("EnvironmentName"),'PrivateDnsZoneId')
      )
`

Apparently, because it's the root stack, the 'else' part is always evaluated, regardless of what I try. 
As I cannot have an 'if' inside the `findInMap`, it doesn't get pretty easy. 

I'd need major refactoring in the work that was done by Base2 previously to get that to work. 

While I understand you want to keep your common templates lean and it makes sense, from my point of view that means I'd need to just keep my own fork from now on.

**Comment by cintiadrrezdy** [comment]
We decided to fork this component moving forward (which means you can undo the previous PR as well)

**Pull request closed without merging**
